"""Base types and ABC for Matter knowledge graph implementations.

All concrete knowledge graph backends (local NetworkX, Docker HTTP client)
must implement ``BaseKnowledgeGraph``.  Shared enums and dataclasses live here
to avoid circular imports between ``graph_builder.py`` and ``docker_graph.py``.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional

from src.loader.base_loader import Document


# ---------------------------------------------------------------------------
# Shared types
# ---------------------------------------------------------------------------

class NodeType(str, Enum):
    # Schema entities (from Matter DM XML — authoritative source of truth)
    CLUSTER         = "CLUSTER"
    ATTRIBUTE       = "ATTRIBUTE"
    COMMAND         = "COMMAND"
    EVENT           = "EVENT"
    FEATURE         = "FEATURE"
    # Protocol / behaviour backbone
    PROTOCOL_AREA   = "PROTOCOL_AREA"
    BEHAVIOR        = "BEHAVIOR"
    # Spec / normative knowledge
    REQUIREMENT     = "REQUIREMENT"
    BEHAVIOR_RULE   = "BEHAVIOR_RULE"
    # Test plan knowledge
    TEST_CASE       = "TEST_CASE"
    PICS_ITEM       = "PICS_ITEM"
    # Generic / structural
    SECTION         = "SECTION"
    # System-prompt consolidation — holds pre-built spec reference text for LLM prompts
    PROMPT_SECTION  = "PROMPT_SECTION"
    # Online / transient
    PR_CHANGE       = "PR_CHANGE"


class EdgeType(str, Enum):
    # ── Data-model backbone ──────────────────────────────────────────────────
    # Directed from CLUSTER outward: CLUSTER →[HAS_*]→ entity
    HAS_ATTRIBUTE  = "HAS_ATTRIBUTE"
    HAS_COMMAND    = "HAS_COMMAND"
    HAS_EVENT      = "HAS_EVENT"
    HAS_FEATURE    = "HAS_FEATURE"
    # Reserved for future layers:
    #   CLUSTER  →[HAS_REQUIREMENT]→   REQUIREMENT
    #   CLUSTER  →[HAS_BEHAVIOR_RULE]→ BEHAVIOR_RULE
    #   PROTOCOL_AREA →[HAS_CLUSTER]→  CLUSTER

    # ── Traceability ─────────────────────────────────────────────────────────
    COVERS         = "covers"        # test_case → requirement / schema entity
    TESTS          = "tests"         # test_case → cluster / attribute
    VALIDATES      = "validates"     # test_case → requirement
    IMPLEMENTS     = "implements"    # requirement → schema entity

    # ── TC → schema entity (precise, generated by kb_graph_builder) ──────────
    TESTS_COMMAND       = "tests_command"     # test_case → command
    VERIFIES_ATTRIBUTE  = "verifies_attribute"  # test_case → attribute
    VERIFIES_REQUIREMENT = "verifies_requirement"  # test_case → requirement
    VERIFIES_RULE       = "verifies_rule"     # test_case → behavior_rule
    OBSERVES_EVENT      = "observes_event"    # test_case → event

    # ── Change / impact ───────────────────────────────────────────────────────
    IMPACTS        = "impacts"       # pr_change → requirement / schema entity

    # ── Structural ────────────────────────────────────────────────────────────
    BELONGS_TO               = "belongs_to"
    BELONGS_TO_PROTOCOL_AREA = "BELONGS_TO_PROTOCOL_AREA"
    HAS_BEHAVIOR_RULE        = "HAS_BEHAVIOR_RULE"

    # ── Protocol/behavior backbone ────────────────────────────────────────────
    IN_CONTEXT   = "in_context"
    GOVERNS      = "governs"
    HAS_CONDITION = "has_condition"
    HAS_EFFECT   = "has_effect"
    GATED_BY_PICS = "gated_by_pics"

    # ── Fine-grained TC → ATTRIBUTE interaction edges ────────────────────────
    # These replace the coarse VERIFIES_ATTRIBUTE for read/write/validate so that
    # impact queries like "find tests that validate_range for Foo.Bar" work precisely.
    READS               = "reads"               # TC reads an attribute value
    WRITES              = "writes"              # TC writes an attribute value
    VALIDATES_TYPE      = "validates_type"      # TC validates attribute data type
    VALIDATES_RANGE     = "validates_range"     # TC validates value range / bounds
    VALIDATES_DEFAULT   = "validates_default"   # TC validates default value
    VALIDATES_QUIETER_REPORTING = "validates_quieter_reporting"  # TC validates quieter reporting behaviour
    VALIDATES_ENUM      = "validates_enum"      # TC validates enum / value list
    VALIDATES_ACCESS    = "validates_access"    # TC validates access control / ACL
    VALIDATES_CONFORMANCE = "validates_conformance"  # TC validates feature conformance / PICS

    # ── Fine-grained TC → entity interaction edges (broader) ─────────────────
    NEGATIVE_TESTS      = "negative_tests"      # TC tests negative / error scenario
    DEPENDS_ON          = "depends_on"          # TC validates cross-entity dependency

    # ── Misc ──────────────────────────────────────────────────────────────────
    REFERENCES     = "references"
    DERIVED_FROM   = "derived_from"
    CONFLICTS_WITH = "conflicts_with"
    RELATED_TO     = "related_to"
    ALIAS_OF       = "alias_of"      # alias CLUSTER node → base CLUSTER node


class ChangeKind(str, Enum):
    """Categories of changes a PR can make to a Matter entity.

    Used by ``MatterKGBuilder.analyze_impact_for_change()`` to map the change
    to the set of edge types that most directly connect a test case to the
    affected entity.
    """
    ENTITY_ADDED          = "entity_added"
    ENTITY_REMOVED        = "entity_removed"
    DATATYPE_CHANGED      = "datatype_changed"
    CONSTRAINT_CHANGED    = "constraint_changed"
    DEFAULT_CHANGED       = "default_changed"
    QUIETER_REPORTING_CHANGED = "quieter_reporting_changed"
    ENUM_CHANGED          = "enum_changed"
    ACCESS_CHANGED        = "access_changed"
    CONFORMANCE_CHANGED   = "conformance_changed"
    BEHAVIOR_CHANGED      = "behavior_changed"
    DEPENDENCY_CHANGED    = "dependency_changed"
    STATE_MACHINE_CHANGED = "state_machine_changed"


@dataclass
class GraphNode:
    node_id: str
    node_type: NodeType
    label: str
    properties: dict = field(default_factory=dict)


@dataclass
class GraphEdge:
    source: str
    target: str
    edge_type: EdgeType
    properties: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------

class BaseKnowledgeGraph(ABC):
    """Contract that every knowledge graph backend must satisfy."""

    @abstractmethod
    def add_data_model_documents(self, documents: List[Document]) -> None:
        """Ingest Matter data-model XML documents — creates canonical schema nodes.

        Creates CLUSTER / COMMAND / ATTRIBUTE / EVENT / FEATURE nodes from the
        structured metadata stored in ``doc.metadata['schema']`` by
        ``MatterXMLFetcher``.  Falls back to text-based entity extraction when
        ``schema`` metadata is absent.
        """

    @abstractmethod
    def add_test_plan_documents(self, documents: List[Document]) -> None:
        """Ingest test plan documents into the graph."""

    @abstractmethod
    def add_pr_documents(self, documents: List[Document]) -> None:
        """Ingest PR change documents into the graph."""

    @abstractmethod
    def add_spec_documents(self, documents: List[Document]) -> None:
        """Ingest Matter specification documents — creates REQUIREMENT/SECTION nodes."""

    @abstractmethod
    def extract_matter_entities(self, documents: List[Document]) -> None:
        """Extract Matter-specific entities (clusters, commands, attributes)."""

    @abstractmethod
    def search_by_entities(self, text: str, max_results: int = 10) -> List[GraphNode]:
        """Find TEST_CASE / REQUIREMENT nodes matching Matter entities in *text*."""

    def search_by_keywords(
        self,
        keywords: List[str],
        node_types: "Optional[List[NodeType]]" = None,
        requirement_types: "Optional[List[str]]" = None,
        max_results: int = 10,
    ) -> List[GraphNode]:
        """Full-text keyword search over node labels and content.

        Unlike ``search_by_entities`` which requires entity names in specific
        capitalisation formats, this method accepts plain lowercase keywords and
        searches across all content-bearing node types.  Useful for natural-language
        chat queries like ``["timer", "protocol", "requirements"]``.

        When ``requirement_types`` is given (e.g. ``["timing_requirement"]``), only
        REQUIREMENT / BEHAVIOR_RULE nodes whose ``properties["requirement_type"]``
        matches are returned; TEST_CASE nodes are unaffected by this filter.

        Default implementation falls back to ``search_by_entities`` using the
        joined keywords.  Subclasses can override for a more efficient scan.

        Args:
            keywords:          Lowercase words to search for (stop words already removed).
            node_types:        Which NodeTypes to include.  ``None`` → REQUIREMENT,
                               BEHAVIOR_RULE, TEST_CASE.
            requirement_types: Requirement type string filter (e.g. ``["timing_requirement"]``).
                               ``None`` → no filtering.
            max_results:       Maximum results to return.

        Returns:
            List of GraphNode sorted by descending keyword-hit count.
        """
        return self.search_by_entities(" ".join(keywords), max_results=max_results)

    @abstractmethod
    def get_coverage_gaps(self) -> List[GraphNode]:
        """Return PR_CHANGE nodes with no linked test case nodes."""

    @abstractmethod
    def load_from_json(self, path: str) -> None:
        """Restore a previously saved graph from a JSON file."""

    @property
    @abstractmethod
    def num_nodes(self) -> int:
        """Total node count."""

    @property
    @abstractmethod
    def num_edges(self) -> int:
        """Total edge count."""
